development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dressinfun.com
  pool: 5
  username: dressinfun.com
  password: a29y6j78
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dressinfun_com_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dressinfun.com
  pool: 5
  username: dressinfun.com
  password: a29y6j78
  socket: /tmp/mysql.sock
